[package]
name = "dartforge-gerador-ng"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
dartforge-frontend = { path = "../frontend" }
dartforge-intern = { path = "../intern" }
dartforge-elements = { path = "../elements" }
