void main() {
  int a = 7;
  int b = 2;
  double d = 2.5;
  num n = 3;
  bool t = true;
  String s = 'ola';
  var x = null;
  print(a + b);
  print(a - b);
  print(a * b);
  print(a / b);
  print(a ~/ b);
  print(a % b);
  print(-7 % 3);
  print(a << b);
  print(a >> b);
  print(a >>> b);
  print(a & b);
  print(a | b);
  print(a ^ b);
  print(-a);
  print(a < b);
  print(a <= b);
  print(a == b);
  print(a != b);
  print(d + a);
  print(n * 2);
  print(d ~/ 1);
  print(s + ' mundo');
  print(s == 'ola');
  print(s.length);
  print(s.toUpperCase());
  print('a$a b${a + b} \n\t\u{1F600} \$ \\ "q" \'z\'');
  print(t && !t || a > b);
  print(a > b ? 'sim' : 'nao');
  print(x ?? 'nulo');
  print(x);
  var i = 0;
  while (i < 3) { i++; }
  do { i--; } while (i > 0);
  for (var j = 0; j < 3; j++) { if (j == 1) continue; print(j); }
  for (final e in [1, 2, 3]) { print(e); }
  outer: for (var k = 0; k < 3; k++) { for (var l = 0; l < 3; l++) { if (l == 2) continue outer; if (k == 2) break outer; print('$k$l'); } }
  switch (a) { case 1: print('um'); break; case 7: case 8: print('sete'); break; default: print('outro'); }
  switch (s) { case 'ola': print('oi'); default: print('?'); }
  a += 3; a -= 1; a *= 2; a ~/= 2; a++; ++a; a--; --a;
  print(a);
  int? m;
  m ??= 5;
  print(m);
  print(a.isEven);
  print(a.toString());
  print(d.toStringAsFixed(2));
  print(1 + 2.5);
  print(a.abs());
  print(s.substring(1));
  print(s[0]);
  print(s * 2);
  print(-d);
  print(a.compareTo(b));
  print(s.codeUnitAt(0));
  print(s.contains('l'));
  print(3.7.floor());
  print(3.2.ceil());
  print(3.5.round());
  print(10.clamp(1, 5));
  print(2.5 * 3);
  print(7 / 2 > 3);
  print('abc'.indexOf('c'));
  print('a,b'.split(','));
  print('  x '.trim());
  print('x'.isEmpty);
  print('x'.padLeft(3, '0'));
  print('Hello'.replaceAll('l', 'L'));
  print('abc'.startsWith('ab'));
  print(int.parse('42') + 1);
  print(double.parse('1.5'));
  print('${1 == 1.0}');
  print(identical(1, 1));
  var big = 1000000;
  print(big * 1000);
  print(0xFF);
  print('multi'
      'line');
  print("""tri
ple""");
  print(r'raw\n$x');
  print(true.toString() + false.toString());
  print(null == null);
  int c = 5;
  c = c > 3 ? c * 2 : c;
  print(c);
  bool f = false;
  f = !f;
  print(f);
  print(5 > 3 && 2 < 1);
  print((5).hashCode == 5.hashCode);
  print('é'.length);
  print('😀'.length);
  print('\u{1F600}'.codeUnits);
  print('ab'.codeUnits);
  print(String.fromCharCode(65));
  print(9007199254740991);
  print(-9007199254740991);
  var count = 0;
  for (var q = 10; q > 0; q -= 3) count += q;
  print(count);
  var w = 1;
  w <<= 3;
  w |= 1;
  w &= 0xF;
  w ^= 2;
  w %= 5;
  print(w);
  int? nn = null;
  print(nn?.isEven);
  print(nn ?? 4);
  print(a > 1 ? a < 10 ? 'meio' : 'alto' : 'baixo');
}
