void main() {
  var l = [1, 2, 3];
  var ls = <String>['a', 'b'];
  List<double> ld = [1.5];
  var m = {'a': 1, 'b': 2};
  Map<String, List<int>> mm = {'x': [1]};
  var s = {1, 2, 3};
  Set<String> ss = <String>{};
  var empty = [];
  var emptyMap = {};
  var l2 = [...l, 4, if (l.length > 2) 5, for (var i in l) i * 10, ...?null];
  var m2 = {...m, 'c': 3, if (true) 'd': 4, for (var k in ['e']) k: 5};
  var s2 = {...s, 9};
  print(l);
  print(ls);
  print(ld);
  print(m);
  print(mm);
  print(s);
  print(ss);
  print(empty);
  print(emptyMap);
  print(l2);
  print(m2);
  print(s2);
  print(l[0]);
  l[0] = 10;
  print(l);
  print(m['a']);
  m['z'] = 26;
  print(m);
  print(m.length);
  print(m.keys);
  print(m.values.toList());
  print(m.containsKey('a'));
  print(l.length);
  l.add(7);
  l.addAll([8, 9]);
  print(l);
  print(l.contains(7));
  print(l.indexOf(7));
  print(l.first);
  print(l.last);
  print(l.isEmpty);
  print(l.reversed.toList());
  print(l.where((e) => e > 5).toList());
  print(l.map((e) => '$e!').join(','));
  print(l.any((e) => e == 8));
  print(l.every((e) => e > 0));
  print(l.take(2).toList());
  print(l.skip(4).toList());
  print(l.sublist(1, 3));
  l.removeAt(0);
  l.remove(9);
  print(l);
  l.insert(0, 100);
  print(l);
  print(l.reduce((a, b) => a + b));
  l.sort();
  print(l);
  l.clear();
  print(l);
  Iterable<int> it = [3, 4];
  print(it.length);
  print(it.first);
  for (var x in it) print(x);
  print(it.map((e) => e + 1));
  s.add(4);
  s.remove(1);
  print(s.contains(2));
  print(s.length);
  print(s.toList());
  m.forEach((k, v) { print('$k=$v'); });
  for (var e in m.entries) print('${e.key}:${e.value}');
  m.remove('a');
  print(m);
  print(m.isEmpty);
  var nested = [[1, 2], [3]];
  print(nested[1][0]);
  print(nested.expand((e) => e).toList());
  var gen = List.generate(3, (i) => i * i);
  print(gen);
  var filled = List.filled(2, 'x');
  print(filled);
  print(List<int>.from([1, 2]));
  print('abc'.split('').reversed.join());
  print([1, 2, 3].asMap());
  var str = ['x', 'y'].join('-');
  print(str);
  print(l2.runtimeType);
  print(l2 is List<int>);
  print(m is Map<String, int>);
  print(<int, String>{} is Map<int, String>);
  print(ss is Set<String>);
  print(const [1, 2]);
  print(const {'a': 1});
  const cl = [1];
  print(identical(cl, const [1]));
  print(l2.getRange(0, 2).toList());
  print(m.putIfAbsent('q', () => 0));
  print(m.update('q', (v) => v + 1));
  print(l2.firstWhere((e) => e > 3));
  print(l2.lastIndexOf(4));
  print(l2.toSet().length);
  print(l2.fold<int>(0, (a, b) => a + b));
  print([3, 1, 2]..sort());
  print(m.map((k, v) => MapEntry(v, k)));
  print(m.entries.map((e) => e.key).toList());
  print([1, 2, 3].indexed.toList());
  print('hello'.characters);
}
extension on String {
  Iterable<String> get characters => split('');
}
