[package]
name = "dartforge-semantic"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[lints]
workspace = true
[dependencies]
dartforge-diagnostics = { path = "../diagnostics" }
dartforge-syntax = { path = "../syntax" }

[dev-dependencies]
dartforge-parser = { path = '../parser' }
dartforge-lexer = { path = '../lexer' }
