[package]
name = "dartforge-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[lints]
workspace = true
[dependencies]
dartforge-abi = { path = "../abi" }
dartforge-native = { path = "../native" }
dartforge-jit = { path = "../jit" }
dartforge-compiler = { path = "../compiler" }
dartforge-packages = { path = "../packages" }
serde_json = "1"

[[bin]]
name = "dartforge"
path = "src/main.rs"
