[package]
name = "dartforge-diferencial"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
dartforge-emit-native = { path = "../emit_native" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "dartforge-diferencial"
path = "src/main.rs"
