[package]
name = "dartforge-linker"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[lints]
workspace = true
[dependencies]
dartforge-diagnostics = { path = "../diagnostics" }
dartforge-syntax = { path = "../syntax" }
dartforge-lexer = { path = "../lexer" }
dartforge-parser = { path = "../parser" }
dartforge-packages = { path = "../packages" }
dartforge-semantic = { path = "../semantic" }
dartforge-optimizer = { path = "../optimizer" }
dartforge-hir = { path = "../hir" }
dartforge-codegen = { path = "../codegen" }
