name: corpus_macros_discovery
publish_to: none
environment:
  sdk: ^3.6.0
dependencies:
  json: 0.20.4
dev_dependencies:
  analyzer: 7.3.0
  build_runner: 2.4.15
  dartforge_macros_builder:
    path: ../../../pacotes/macros_builder
  corpus_macros_registry:
    path: ../macros_registry
  macros:
    path: ../../../pacotes/macros
dependency_overrides:
  macros:
    path: ../../../pacotes/macros
