[package]
name = "dartforge-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[lints]
workspace = true
[dependencies]
dartforge-compiler = { path = "../compiler" }
dartforge-diagnostics = { path = "../diagnostics" }
[dev-dependencies]
dartforge-instrument = { path = "../instrument" }
