[package]
name = "dartforge-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[lints]
workspace = true
[dependencies]
dartforge-diagnostics = { path = "../diagnostics" }
dartforge-analise = { path = "../analise" }
dartforge-elements = { path = "../elements" }
dartforge-frontend = { path = "../frontend" }
dartforge-intern = { path = "../intern" }
dartforge-types = { path = "../types" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
[dev-dependencies]
dartforge-instrument = { path = "../instrument" }
