[package]
name = "dartforge-emit-js"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
dartforge-diagnostics = { path = "../diagnostics" }
dartforge-intern = { path = "../intern" }
dartforge-frontend = { path = "../frontend" }
dartforge-elements = { path = "../elements" }
dartforge-gerador-ng = { path = "../gerador_ng" }
dartforge-types = { path = "../types" }

[dev-dependencies]
tempfile = "3"
dartforge-instrument = { path = "../instrument" }
