//! Gerado por scripts/gerar-especies-de-acao.py a partir de
//! docs/LSP-ESPECIFICACAO.md (§13.7.2 e a tabela de `DartAssistKind`).
//! Não editar à mão.

/// (id, prioridade, mensagem), em ordem de id.
pub(crate) const ESPECIES: &[(&str, u16, &str)] = &[
    ("dart.assist.add.diagnosticPropertyReference", 30, "Add a debug reference to this property"),
    ("dart.assist.add.digitSeparators", 30, "Add digit separators"),
    ("dart.assist.add.returnType", 30, "Add return type"),
    ("dart.assist.add.showCombinator", 30, "Add explicit 'show' combinator"),
    ("dart.assist.add.typeAnnotation", 30, "Add type annotation"),
    ("dart.assist.assignToVariable", 30, "Assign value to new local variable"),
    ("dart.assist.convert.blockComment", 30, "Convert to block documentation comment"),
    ("dart.assist.convert.bodyToAsync", 31, "Convert to async function body"),
    ("dart.assist.convert.bodyToBlock", 30, "Convert to block body"),
    ("dart.assist.convert.bodyToExpression", 30, "Convert to expression body"),
    ("dart.assist.convert.classToEnum", 30, "Convert class to an enum"),
    ("dart.assist.convert.classToMixin", 30, "Convert class to a mixin"),
    ("dart.assist.convert.conditionalToIfElse", 30, "Replace conditional with 'if-else'"),
    ("dart.assist.convert.finalFieldToGetter", 30, "Convert to getter"),
    ("dart.assist.convert.forEachToForIndex", 30, "Convert to for-index loop"),
    ("dart.assist.convert.getterToFinalField", 30, "Convert to final field"),
    ("dart.assist.convert.ifCaseStatement", 30, "Convert to 'if-case' statement"),
    ("dart.assist.convert.ifCaseStatementChain", 30, "Convert to 'if-case' statement chain"),
    ("dart.assist.convert.ifElseToConditional", 30, "Replace 'if-else' with conditional ('c ? x : y')"),
    ("dart.assist.convert.isNot", 30, "Convert to is!"),
    ("dart.assist.convert.isNotEmpty", 30, "Convert to 'isNotEmpty'"),
    ("dart.assist.convert.lineComment", 30, "Convert to line documentation comment"),
    ("dart.assist.convert.packageToRelativeImport", 30, "Convert to a relative import"),
    ("dart.assist.convert.partOfToPartUri", 30, "Convert to use a URI"),
    ("dart.assist.convert.relativeToPackageImport", 30, "Convert to 'package:' import"),
    ("dart.assist.convert.switchExpression", 30, "Convert to switch expression"),
    ("dart.assist.convert.switchStatement", 30, "Convert to switch statement"),
    ("dart.assist.convert.toConstructorFieldParameter", 30, "Convert to field formal parameter"),
    ("dart.assist.convert.toConstructorNormalParameter", 30, "Convert to normal parameter"),
    ("dart.assist.convert.toDoubleQuotedString", 30, "Convert to double quoted string"),
    ("dart.assist.convert.toForElement", 30, "Convert to a 'for' element"),
    ("dart.assist.convert.toGenericFunctionSyntax", 30, "Convert into 'Function' syntax"),
    ("dart.assist.convert.toIfElement", 30, "Convert to an 'if' element"),
    ("dart.assist.convert.toIntLiteral", 30, "Convert to an int literal"),
    ("dart.assist.convert.toMapLiteral", 30, "Convert to map literal"),
    ("dart.assist.convert.toMultilineString", 30, "Convert to multiline string"),
    ("dart.assist.convert.toNullAware", 30, "Convert to use '?.'"),
    ("dart.assist.convert.toSetLiteral", 30, "Convert to set literal"),
    ("dart.assist.convert.toSingleQuotedString", 30, "Convert to single quoted string"),
    ("dart.assist.convert.toSpread", 30, "Convert to a spread"),
    ("dart.assist.convert.toSuperParameters", 30, "Convert to using super parameters"),
    ("dart.assist.destructureLocalVariableAssignment", 30, "Destructure variable assignment"),
    ("dart.assist.encapsulateField", 30, "Encapsulate field"),
    ("dart.assist.exchangeOperands", 30, "Exchange operands"),
    ("dart.assist.flutter.convert.childToChildren", 30, "Convert to children:"),
    ("dart.assist.flutter.convert.toStatefulWidget", 30, "Convert to StatefulWidget"),
    ("dart.assist.flutter.convert.toStatelessWidget", 30, "Convert to StatelessWidget"),
    ("dart.assist.flutter.move.down", 26, "Move widget down"),
    ("dart.assist.flutter.move.up", 26, "Move widget up"),
    ("dart.assist.flutter.removeWidget", 25, "Remove this widget"),
    ("dart.assist.flutter.swap.withChild", 27, "Swap with child"),
    ("dart.assist.flutter.swap.withParent", 27, "Swap with parent"),
    ("dart.assist.flutter.wrap.builder", 28, "Wrap with Builder"),
    ("dart.assist.flutter.wrap.center", 28, "Wrap with Center"),
    ("dart.assist.flutter.wrap.column", 28, "Wrap with Column"),
    ("dart.assist.flutter.wrap.container", 28, "Wrap with Container"),
    ("dart.assist.flutter.wrap.generic", 29, "Wrap with widget..."),
    ("dart.assist.flutter.wrap.padding", 28, "Wrap with Padding"),
    ("dart.assist.flutter.wrap.row", 28, "Wrap with Row"),
    ("dart.assist.flutter.wrap.sizedBox", 28, "Wrap with SizedBox"),
    ("dart.assist.flutter.wrap.streamBuilder", 28, "Wrap with StreamBuilder"),
    ("dart.assist.inline", 30, "Inline invocation of '{0}'"),
    ("dart.assist.invertConditional", 30, "Invert conditional expression"),
    ("dart.assist.invertIf", 30, "Invert 'if' statement"),
    ("dart.assist.joinVariableDeclaration", 30, "Join variable declaration"),
    ("dart.assist.joinWithInnerIf", 30, "Join 'if' statement with inner 'if' statement"),
    ("dart.assist.joinWithOuterIf", 30, "Join 'if' statement with outer 'if' statement"),
    ("dart.assist.remove.digitSeparators", 30, "Remove digit separators"),
    ("dart.assist.remove.typeAnnotation", 31, "Remove type annotation"),
    ("dart.assist.replace.withVar", 30, "Replace type annotation with 'var'"),
    ("dart.assist.shadowField", 30, "Create a local variable that shadows the field"),
    ("dart.assist.sort.child.properties.last", 30, "Move child property to end of arguments"),
    ("dart.assist.splitIfConjunction", 30, "Split && condition"),
    ("dart.assist.splitVariableDeclaration", 30, "Split variable declaration"),
    ("dart.assist.surround.block", 38, "Surround with block"),
    ("dart.assist.surround.curlyBraces", 30, "Use curly braces"),
    ("dart.assist.surround.doWhile", 33, "Surround with 'do-while'"),
    ("dart.assist.surround.forEach", 34, "Surround with 'for'"),
    ("dart.assist.surround.forIn", 35, "Surround with 'for-in'"),
    ("dart.assist.surround.if", 37, "Surround with 'if'"),
    ("dart.assist.surround.setState", 33, "Surround with 'setState'"),
    ("dart.assist.surround.tryCatch", 32, "Surround with 'try-catch'"),
    ("dart.assist.surround.tryFinally", 31, "Surround with 'try-finally'"),
    ("dart.assist.surround.while", 36, "Surround with 'while'"),
    ("dart.assist.unwrap.if", 30, "Unwrap 'if' body"),
    ("dart.fix.add.async", 50, "Add 'async' modifier"),
    ("dart.fix.add.await", 50, "Add 'await' keyword"),
    ("dart.fix.add.await.multi", 40, "Add 'await's everywhere in file"),
    ("dart.fix.add.callSuper", 50, "Add 'super.{0}'"),
    ("dart.fix.add.class.modifier.base", 50, "Add 'base' modifier"),
    ("dart.fix.add.class.modifier.base.multi", 40, "Add 'base' modifier everywhere in file"),
    ("dart.fix.add.class.modifier.final", 50, "Add 'final' modifier"),
    ("dart.fix.add.class.modifier.final.multi", 40, "Add 'final' modifier everywhere in file"),
    ("dart.fix.add.class.modifier.sealed", 50, "Add 'sealed' modifier"),
    ("dart.fix.add.class.modifier.sealed.multi", 40, "Add 'sealed' modifier everywhere in file"),
    ("dart.fix.add.const", 50, "Add 'const' modifier"),
    ("dart.fix.add.const.multi", 40, "Add 'const' modifiers everywhere in file"),
    ("dart.fix.add.curlyBraces", 50, "Add curly braces"),
    ("dart.fix.add.curlyBraces.multi", 40, "Add curly braces everywhere in file"),
    ("dart.fix.add.diagnosticPropertyReference", 50, "Add a debug reference to this property"),
    ("dart.fix.add.diagnosticPropertyReference.multi", 40, "Add missing debug property references everywhere in file"),
    ("dart.fix.add.empty.argument.list", 50, "Add empty argument list"),
    ("dart.fix.add.empty.argument.list.multi", 40, "Add empty argument lists everywhere in file"),
    ("dart.fix.add.enumConstant", 50, "Add enum constant '{0}'"),
    ("dart.fix.add.eolAtEndOfFile", 50, "Add EOL at end of file"),
    ("dart.fix.add.explicitCall", 50, "Add explicit .call tearoff"),
    ("dart.fix.add.explicitCall.multi", 40, "Add explicit .call to implicit tearoffs in file"),
    ("dart.fix.add.explicitCast", 50, "Add cast"),
    ("dart.fix.add.explicitCast.multi", 40, "Add cast everywhere in file"),
    ("dart.fix.add.extensionOverride", 50, "Add an extension override for '{0}'"),
    ("dart.fix.add.fieldFormalParameters", 70, "Add final field formal parameters"),
    ("dart.fix.add.keyToConstructors", 50, "Add 'key' to constructors"),
    ("dart.fix.add.keyToConstructors.multi", 50, "Add 'key' to constructors everywhere in file"),
    ("dart.fix.add.late", 50, "Add 'late' modifier"),
    ("dart.fix.add.leadingNewlineToString", 50, "Add leading new line"),
    ("dart.fix.add.leadingNewlineToString.multi", 50, "Add leading new line everywhere in file"),
    ("dart.fix.add.missingEnumCaseClauses", 50, "Add missing case clauses"),
    ("dart.fix.add.missingParameterNamed", 70, "Add named parameter '{0}'"),
    ("dart.fix.add.missingParameterPositional", 69, "Add optional positional parameter"),
    ("dart.fix.add.missingParameterRequired", 70, "Add required positional parameter"),
    ("dart.fix.add.missingRequiredArgument", 70, "Add required argument '{0}'"),
    ("dart.fix.add.missingSwitchCases", 50, "Add missing switch cases"),
    ("dart.fix.add.neNull", 50, "Add != null"),
    ("dart.fix.add.neNull.multi", 40, "Add != null everywhere in file"),
    ("dart.fix.add.nullCheck", 49, "Add a null check (!)"),
    ("dart.fix.add.override", 50, "Add '@override' annotation"),
    ("dart.fix.add.override.multi", 40, "Add '@override' annotations everywhere in file"),
    ("dart.fix.add.redeclare", 50, "Add '@redeclare' annotation"),
    ("dart.fix.add.redeclare.multi", 40, "Add '@redeclare' annotations everywhere in file"),
    ("dart.fix.add.reopen", 50, "Add '@reopen' annotation"),
    ("dart.fix.add.reopen.multi", 40, "Add '@reopen' annotations everywhere in file"),
    ("dart.fix.add.required", 50, "Add 'required' keyword"),
    ("dart.fix.add.returnNull", 50, "Add 'return null'"),
    ("dart.fix.add.returnNull.multi", 40, "Add 'return null' everywhere in file"),
    ("dart.fix.add.returnType", 50, "Add return type"),
    ("dart.fix.add.returnType.multi", 40, "Add return types everywhere in file"),
    ("dart.fix.add.static", 50, "Add 'static' modifier"),
    ("dart.fix.add.superConstructorInvocation", 50, "Add super constructor {0} invocation"),
    ("dart.fix.add.superParameter", 50, "Add required parameter{0}"),
    ("dart.fix.add.switchCaseReturn", 50, "Add 'break'"),
    ("dart.fix.add.switchCaseReturn.multi", 40, "Add 'break' everywhere in file"),
    ("dart.fix.add.trailingComma", 50, "Add trailing comma"),
    ("dart.fix.add.trailingComma.multi", 40, "Add trailing commas everywhere in file"),
    ("dart.fix.add.typeAnnotation", 50, "Add type annotation"),
    ("dart.fix.add.typeAnnotation.multi", 40, "Add type annotations everywhere in file"),
    ("dart.fix.change.argumentName", 60, "Change to '{0}'"),
    ("dart.fix.change.to", 51, "Change to '{0}'"),
    ("dart.fix.change.toNearestPreciseValue", 50, "Change to nearest precise int-as-double value: {0}"),
    ("dart.fix.change.toStaticAccess", 50, "Change access to static using '{0}'"),
    ("dart.fix.change.typeAnnotation", 50, "Change '{0}' to '{1}' type annotation"),
    ("dart.fix.convert.bodyToBlock", 50, "Convert to block body"),
    ("dart.fix.convert.bodyToBlock.multi", 40, "Convert to block body everywhere in file"),
    ("dart.fix.convert.classToEnum", 50, "Convert class to an enum"),
    ("dart.fix.convert.classToEnum.multi", 50, "Convert classes to enums in file"),
    ("dart.fix.convert.isNot", 50, "Convert to is!"),
    ("dart.fix.convert.isNot.multi", 40, "Convert to is! everywhere in file"),
    ("dart.fix.convert.quotes", 50, "Convert the quotes and remove escapes"),
    ("dart.fix.convert.quotes.multi", 40, "Convert the quotes and remove escapes everywhere in file"),
    ("dart.fix.convert.toBoolExpression", 50, "Convert to boolean expression"),
    ("dart.fix.convert.toBoolExpression.multi", 50, "Convert to boolean expressions everywhere in file"),
    ("dart.fix.convert.toCascade", 50, "Convert to cascade notation"),
    ("dart.fix.convert.toConstantPattern", 49, "Convert to constant pattern"),
    ("dart.fix.convert.toContains", 50, "Convert to using 'contains'"),
    ("dart.fix.convert.toContains.multi", 40, "Convert to using 'contains' everywhere in file"),
    ("dart.fix.convert.toDoubleQuotedString", 50, "Convert to double quoted string"),
    ("dart.fix.convert.toDoubleQuotedString.multi", 40, "Convert to double quoted strings everywhere in file"),
    ("dart.fix.convert.toExpressionBody", 50, "Convert to expression body"),
    ("dart.fix.convert.toExpressionBody.multi", 40, "Convert to expression bodies everywhere in file"),
    ("dart.fix.convert.toFlutterStyleTodo", 50, "Convert to flutter style todo"),
    ("dart.fix.convert.toFlutterStyleTodo.multi", 40, "Convert to flutter style todos everywhere in file"),
    ("dart.fix.convert.toForElement", 50, "Convert to a 'for' element"),
    ("dart.fix.convert.toForElement.multi", 40, "Convert to 'for' elements everywhere in file"),
    ("dart.fix.convert.toForLoop", 50, "Convert 'forEach' to a 'for' loop"),
    ("dart.fix.convert.toForLoop.multi", 40, "Convert 'forEach' to a 'for' loop everywhere in file"),
    ("dart.fix.convert.toFunctionDeclaration", 50, "Convert to function declaration"),
    ("dart.fix.convert.toFunctionDeclaration.multi", 40, "Convert to function declaration everywhere in file"),
    ("dart.fix.convert.toGenericFunctionSyntax", 50, "Convert into 'Function' syntax"),
    ("dart.fix.convert.toGenericFunctionSyntax.multi", 40, "Convert to 'Function' syntax everywhere in file"),
    ("dart.fix.convert.toIfElement", 50, "Convert to an 'if' element"),
    ("dart.fix.convert.toIfElement.multi", 40, "Convert to 'if' elements everywhere in file"),
    ("dart.fix.convert.toIfNull", 50, "Convert to use '??'"),
    ("dart.fix.convert.toIfNull.multi", 40, "Convert to '??'s everywhere in file"),
    ("dart.fix.convert.toInitializingFormal", 50, "Convert to an initializing formal parameter"),
    ("dart.fix.convert.toIntLiteral", 50, "Convert to an int literal"),
    ("dart.fix.convert.toIntLiteral.multi", 40, "Convert to int literals everywhere in file"),
    ("dart.fix.convert.toLineComment", 50, "Convert to line documentation comment"),
    ("dart.fix.convert.toLineComment.multi", 40, "Convert to line documentation comments everywhere in file"),
    ("dart.fix.convert.toMapLiteral", 50, "Convert to map literal"),
    ("dart.fix.convert.toMapLiteral.multi", 40, "Convert to map literals everywhere in file"),
    ("dart.fix.convert.toNamedArguments", 50, "Convert to named arguments"),
    ("dart.fix.convert.toNullAware", 50, "Convert to use '?.'"),
    ("dart.fix.convert.toNullAware.multi", 40, "Convert to use '?.' everywhere in file"),
    ("dart.fix.convert.toNullAwareSpread", 50, "Convert to use '...?'"),
    ("dart.fix.convert.toNullAwareSpread.multi", 40, "Convert to use '...?' everywhere in file"),
    ("dart.fix.convert.toOnType", 50, "Convert to 'on {0}'"),
    ("dart.fix.convert.toPackageImport", 50, "Convert to 'package:' import"),
    ("dart.fix.convert.toPackageImport.multi", 40, "Convert to 'package:' imports everywhere in file"),
    ("dart.fix.convert.toRawString", 50, "Convert to raw string"),
    ("dart.fix.convert.toRawString.multi", 40, "Convert to raw strings everywhere in file"),
    ("dart.fix.convert.toRelativeImport", 50, "Convert to relative import"),
    ("dart.fix.convert.toRelativeImport.multi", 40, "Convert to relative imports everywhere in file"),
    ("dart.fix.convert.toSetLiteral", 50, "Convert to set literal"),
    ("dart.fix.convert.toSetLiteral.multi", 40, "Convert to set literals everywhere in file"),
    ("dart.fix.convert.toSingleQuotedString", 50, "Convert to single quoted string"),
    ("dart.fix.convert.toSingleQuotedString.multi", 40, "Convert to single quoted strings everywhere in file"),
    ("dart.fix.convert.toSpread", 50, "Convert to a spread"),
    ("dart.fix.convert.toSpread.multi", 40, "Convert to spreads everywhere in file"),
    ("dart.fix.convert.toSuperParameters", 30, "Convert to using super parameters"),
    ("dart.fix.convert.toSuperParameters.multi", 30, "Convert to using super parameters everywhere in file"),
    ("dart.fix.convert.toWhereType", 50, "Convert to use 'whereType'"),
    ("dart.fix.convert.toWhereType.multi", 40, "Convert to using 'whereType' everywhere in file"),
    ("dart.fix.convert.toWildcardPattern", 50, "Convert to wildcard pattern"),
    ("dart.fix.convert.toWildcardVariable", 50, "Convert to wildcard variable"),
    ("dart.fix.create.class", 50, "Create class '{0}'"),
    ("dart.fix.create.constructor", 50, "Create constructor '{0}'"),
    ("dart.fix.create.constructorForFinalFields", 50, "Create constructor for final fields"),
    ("dart.fix.create.constructorForFinalFields.requiredNamed", 50, "Create constructor for final fields, required named"),
    ("dart.fix.create.constructorSuper", 50, "Create constructor to call {0}"),
    ("dart.fix.create.extension.getter", 30, "Create extension getter '{0}'"),
    ("dart.fix.create.extension.method", 30, "Create extension method '{0}'"),
    ("dart.fix.create.extension.setter", 30, "Create extension setter '{0}'"),
    ("dart.fix.create.field", 49, "Create field '{0}'"),
    ("dart.fix.create.file", 50, "Create file '{0}'"),
    ("dart.fix.create.function", 49, "Create function '{0}'"),
    ("dart.fix.create.getter", 50, "Create getter '{0}'"),
    ("dart.fix.create.localVariable", 50, "Create local variable '{0}'"),
    ("dart.fix.create.method", 50, "Create method '{0}'"),
    ("dart.fix.create.method.multi", 40, "Create methods in file"),
    ("dart.fix.create.missingOverrides", 51, "Create {0} missing override{1}"),
    ("dart.fix.create.mixin", 50, "Create mixin '{0}'"),
    ("dart.fix.create.noSuchMethod", 49, "Create 'noSuchMethod' method"),
    ("dart.fix.create.parameter", 50, "Create required positional parameter '{0}'"),
    ("dart.fix.create.setter", 50, "Create setter '{0}'"),
    ("dart.fix.dataDriven", 50, "{0}"),
    ("dart.fix.extendClassForMixin", 50, "Extend the class '{0}'"),
    ("dart.fix.extractLocalVariable", 50, "Extract local variable"),
    ("dart.fix.flutter.convert.childToChildren", 50, "Convert to children:"),
    ("dart.fix.flutter.convert.childrenToChild", 50, "Convert to child:"),
    ("dart.fix.flutter.makeConditionalOnDebugMode", 50, "Make conditional on 'kDebugMode'"),
    ("dart.fix.flutter.wrap.text", 50, "Wrap in a 'Text' widget"),
    ("dart.fix.ignore.analysis", 28, "Ignore '{0}' in `analysis_options.yaml`"),
    ("dart.fix.ignore.file", 29, "Ignore '{0}' for the whole file"),
    ("dart.fix.ignore.line", 30, "Ignore '{0}' for this line"),
    ("dart.fix.import.async", 49, "Import 'dart:async'"),
    ("dart.fix.import.libraryPrefix", 55, "Use imported library '{0}' with prefix '{1}'"),
    ("dart.fix.import.libraryProject1", 53, "Import library '{0}'"),
    ("dart.fix.import.libraryProject2", 52, "Import library '{0}'"),
    ("dart.fix.import.libraryProject3", 51, "Import library '{0}'"),
    ("dart.fix.import.librarySdk", 54, "Import library '{0}'"),
    ("dart.fix.import.libraryShow", 55, "Update library '{0}' import"),
    ("dart.fix.inlineInvocation", 30, "Inline invocation of '{0}'"),
    ("dart.fix.inlineInvocation.multi", 20, "Inline invocations everywhere in file"),
    ("dart.fix.inlineTypedef", 30, "Inline the definition of '{0}'"),
    ("dart.fix.inlineTypedef.multi", 20, "Inline type definitions everywhere in file"),
    ("dart.fix.insertBody", 50, "Insert body"),
    ("dart.fix.insertSemicolon", 50, "Insert ';'"),
    ("dart.fix.insertSemicolon.multi", 40, "Insert ';' everywhere in file"),
    ("dart.fix.makeClassAbstract", 50, "Make class '{0}' abstract"),
    ("dart.fix.makeFieldNotFinal", 50, "Make field '{0}' not final"),
    ("dart.fix.makeFieldPublic", 50, "Make field '{0}' public"),
    ("dart.fix.makeFinal", 50, "Make final"),
    ("dart.fix.makeFinal.multi", 40, "Make final where possible in file"),
    ("dart.fix.makeRequiredNamedParametersFirst", 50, "Put required named parameter first"),
    ("dart.fix.makeRequiredNamedParametersFirst.multi", 40, "Put required named parameters first everywhere in file"),
    ("dart.fix.makeReturnTypeNullable", 50, "Make the return type nullable"),
    ("dart.fix.makeSuperInvocationLast", 50, "Move the invocation to the end of the initializer list"),
    ("dart.fix.makeVariableNotFinal", 50, "Make variable '{0}' not final"),
    ("dart.fix.makeVariableNullable", 50, "Make '{0}' nullable"),
    ("dart.fix.matchAnyMap", 50, "Match any map"),
    ("dart.fix.matchEmptyMap", 50, "Match an empty map"),
    ("dart.fix.moveAnnotationToLibraryDirective", 50, "Move this annotation to a library directive"),
    ("dart.fix.moveDocCommentToLibraryDirective", 50, "Move this doc comment to a library directive"),
    ("dart.fix.moveTypeArgumentsToClass", 50, "Move type arguments to after class name"),
    ("dart.fix.organize.imports", 50, "Organize Imports"),
    ("dart.fix.qualifyReference", 50, "Use '{0}'"),
    ("dart.fix.remove.abstract", 50, "Remove the 'abstract' keyword"),
    ("dart.fix.remove.abstract.multi", 40, "Remove the 'abstract' keyword everywhere in file"),
    ("dart.fix.remove.annotation", 50, "Remove the '{0}' annotation"),
    ("dart.fix.remove.argument", 50, "Remove argument"),
    ("dart.fix.remove.argument.multi", 40, "Remove arguments in file"),
    ("dart.fix.remove.assertion", 50, "Remove the assertion"),
    ("dart.fix.remove.assignment", 50, "Remove assignment"),
    ("dart.fix.remove.assignment.multi", 40, "Remove unnecessary assignments everywhere in file"),
    ("dart.fix.remove.await", 50, "Remove await"),
    ("dart.fix.remove.await.multi", 40, "Remove awaits in file"),
    ("dart.fix.remove.break", 50, "Remove break"),
    ("dart.fix.remove.break.multi", 40, "Remove unnecessary breaks in file"),
    ("dart.fix.remove.character", 50, "Remove the 'U+{0}' code point"),
    ("dart.fix.remove.comma", 50, "Remove the comma"),
    ("dart.fix.remove.comma.multi", 40, "Remove {0}commas from {1} everywhere in file"),
    ("dart.fix.remove.comparison", 50, "Remove comparison"),
    ("dart.fix.remove.comparison.multi", 40, "Remove comparisons in file"),
    ("dart.fix.remove.const", 50, "Remove const"),
    ("dart.fix.remove.constructor", 50, "Remove the constructor"),
    ("dart.fix.remove.constructorName", 50, "Remove 'new'"),
    ("dart.fix.remove.constructorName.multi", 40, "Remove constructor names in file"),
    ("dart.fix.remove.deadCode", 50, "Remove dead code"),
    ("dart.fix.remove.defaultValue", 50, "Remove the default value"),
    ("dart.fix.remove.deprecatedNewInCommentReference", 50, "Remove deprecated new keyword"),
    ("dart.fix.remove.deprecatedNewInCommentReference.multi", 40, "Remove deprecated new keyword in file"),
    ("dart.fix.remove.duplicateCase", 50, "Remove duplicate case statement"),
    ("dart.fix.remove.duplicateCase.multi", 40, "Remove duplicate case statement"),
    ("dart.fix.remove.emptyCatch", 50, "Remove empty catch clause"),
    ("dart.fix.remove.emptyCatch.multi", 40, "Remove empty catch clauses everywhere in file"),
    ("dart.fix.remove.emptyConstructorBody", 50, "Remove empty constructor body"),
    ("dart.fix.remove.emptyConstructorBody.multi", 40, "Remove empty constructor bodies in file"),
    ("dart.fix.remove.emptyElse", 50, "Remove empty else clause"),
    ("dart.fix.remove.emptyElse.multi", 40, "Remove empty else clauses everywhere in file"),
    ("dart.fix.remove.emptyStatement", 50, "Remove empty statement"),
    ("dart.fix.remove.emptyStatement.multi", 40, "Remove empty statements everywhere in file"),
    ("dart.fix.remove.extends.clause", 50, "Remove the invalid 'extends' clause"),
    ("dart.fix.remove.extends.clause.multi", 40, "Remove invalid 'extends' clauses everywhere in file"),
    ("dart.fix.remove.ifNullOperator", 50, "Remove the '??' operator"),
    ("dart.fix.remove.ifNullOperator.multi", 40, "Remove unnecessary '??' operators everywhere in file"),
    ("dart.fix.remove.initializer", 50, "Remove initializer"),
    ("dart.fix.remove.initializer.multi", 40, "Remove unnecessary initializers everywhere in file"),
    ("dart.fix.remove.interpolationBraces", 50, "Remove unnecessary interpolation braces"),
    ("dart.fix.remove.interpolationBraces.multi", 40, "Remove unnecessary interpolation braces everywhere in file"),
    ("dart.fix.remove.invocation", 50, "Remove unnecessary invocation of {0}"),
    ("dart.fix.remove.invocation.multi", 40, "Remove unnecessary invocations of {0} in file"),
    ("dart.fix.remove.late", 50, "Remove the 'late' keyword"),
    ("dart.fix.remove.late.multi", 50, "Remove the 'late' keyword everywhere in file"),
    ("dart.fix.remove.leadingUnderscore", 50, "Remove leading underscore"),
    ("dart.fix.remove.leadingUnderscore.multi", 40, "Remove leading underscores in file"),
    ("dart.fix.remove.lexeme", 50, "Remove the {0} {1}"),
    ("dart.fix.remove.lexeme.multi", 40, "Remove {0}s everywhere in file"),
    ("dart.fix.remove.library.name", 50, "Remove the library name"),
    ("dart.fix.remove.methodDeclaration", 50, "Remove method declaration"),
    ("dart.fix.remove.methodDeclaration.multi", 40, "Remove unnecessary method declarations in file"),
    ("dart.fix.remove.nameFromCombinator", 50, "Remove name from '{0}'"),
    ("dart.fix.remove.nameFromDeclarationClause", 50, "{0}"),
    ("dart.fix.remove.new", 50, "Remove 'new' keyword"),
    ("dart.fix.remove.nonNullAssertion", 50, "Remove the '!'"),
    ("dart.fix.remove.nonNullAssertion.multi", 40, "Remove '!'s in file"),
    ("dart.fix.remove.on.clause", 50, "Remove the invalid 'on' clause"),
    ("dart.fix.remove.on.clause.multi", 40, "Remove all invalid 'on' clauses in file"),
    ("dart.fix.remove.operator", 50, "Remove the operator"),
    ("dart.fix.remove.operator.multi.multi", 40, "Remove operators in file"),
    ("dart.fix.remove.parametersInGetterDeclaration", 50, "Remove parameters in getter declaration"),
    ("dart.fix.remove.parenthesisInGetterInvocation", 50, "Remove parentheses in getter invocation"),
    ("dart.fix.remove.questionMark", 50, "Remove the '?'"),
    ("dart.fix.remove.questionMark.multi", 40, "Remove unnecessary question marks in file"),
    ("dart.fix.remove.removePrint", 50, "Remove print statement"),
    ("dart.fix.remove.removePrint.multi", 40, "Remove print statements in file"),
    ("dart.fix.remove.required", 50, "Remove 'required'"),
    ("dart.fix.remove.returnedValue", 50, "Remove invalid returned value"),
    ("dart.fix.remove.returnedValue.multi", 40, "Remove invalid returned values in file"),
    ("dart.fix.remove.thisExpression", 50, "Remove 'this' expression"),
    ("dart.fix.remove.thisExpression.multi", 40, "Remove unnecessary 'this' expressions everywhere in file"),
    ("dart.fix.remove.typeAnnotation", 50, "Remove type annotation"),
    ("dart.fix.remove.typeAnnotation.multi", 40, "Remove unnecessary type annotations in file"),
    ("dart.fix.remove.typeArguments", 49, "Remove type arguments"),
    ("dart.fix.remove.typeCheck", 50, "Remove type check"),
    ("dart.fix.remove.unexpectedUnderscores", 50, "Remove unexpected '_' characters"),
    ("dart.fix.remove.unexpectedUnderscores.multi", 50, "Remove unexpected '_' characters in file"),
    ("dart.fix.remove.unnecessaryCast", 50, "Remove unnecessary cast"),
    ("dart.fix.remove.unnecessaryCast.multi", 40, "Remove all unnecessary casts in file"),
    ("dart.fix.remove.unnecessaryConst", 50, "Remove unnecessary const keyword"),
    ("dart.fix.remove.unnecessaryConst.multi", 40, "Remove unnecessary 'const' keywords everywhere in file"),
    ("dart.fix.remove.unnecessaryContainer", 50, "Remove unnecessary 'Container'"),
    ("dart.fix.remove.unnecessaryContainer.multi", 40, "Remove unnecessary 'Container's in file"),
    ("dart.fix.remove.unnecessaryFinal", 50, "Remove unnecessary 'final'"),
    ("dart.fix.remove.unnecessaryFinal.multi", 40, "Remove all unnecessary 'final's in file"),
    ("dart.fix.remove.unnecessaryLate", 50, "Remove unnecessary 'late' keyword"),
    ("dart.fix.remove.unnecessaryLate.multi", 40, "Remove unnecessary 'late' keywords everywhere in file"),
    ("dart.fix.remove.unnecessaryLibraryDirective", 50, "Remove unnecessary library directive"),
    ("dart.fix.remove.unnecessaryNew", 50, "Remove unnecessary 'new' keyword"),
    ("dart.fix.remove.unnecessaryNew.multi", 40, "Remove unnecessary 'new' keywords everywhere in file"),
    ("dart.fix.remove.unnecessaryParentheses", 50, "Remove unnecessary parentheses"),
    ("dart.fix.remove.unnecessaryParentheses.multi", 40, "Remove all unnecessary parentheses in file"),
    ("dart.fix.remove.unnecessaryRawString", 50, "Remove unnecessary 'r' in string"),
    ("dart.fix.remove.unnecessaryRawString.multi", 40, "Remove unnecessary 'r' in strings in file"),
    ("dart.fix.remove.unnecessaryStringEscape", 50, "Remove unnecessary '\\' in string"),
    ("dart.fix.remove.unnecessaryStringEscape.multi", 40, "Remove unnecessary '\\' in strings in file"),
    ("dart.fix.remove.unnecessaryStringInterpolation", 50, "Remove unnecessary string interpolation"),
    ("dart.fix.remove.unnecessaryStringInterpolation.multi", 40, "Remove all unnecessary string interpolations in file"),
    ("dart.fix.remove.unnecessaryToList", 50, "Remove unnecessary 'toList' call"),
    ("dart.fix.remove.unnecessaryToList.multi", 40, "Remove unnecessary 'toList' calls in file"),
    ("dart.fix.remove.unnecessaryWildcardPattern", 50, "Remove unnecessary wildcard pattern"),
    ("dart.fix.remove.unnecessaryWildcardPattern.multi", 50, "Remove all unnecessary wildcard pattern in file"),
    ("dart.fix.remove.unusedCatchClause", 50, "Remove unused 'catch' clause"),
    ("dart.fix.remove.unusedCatchClause.multi", 40, "Remove unused 'catch' clauses in file"),
    ("dart.fix.remove.unusedCatchStack", 50, "Remove unused stack trace variable"),
    ("dart.fix.remove.unusedCatchStack.multi", 40, "Remove unused stack trace variables in file"),
    ("dart.fix.remove.unusedElement", 50, "Remove unused element"),
    ("dart.fix.remove.unusedField", 50, "Remove unused field"),
    ("dart.fix.remove.unusedImport", 50, "Remove unused import"),
    ("dart.fix.remove.unusedImport.multi", 40, "Remove all unused imports in file"),
    ("dart.fix.remove.unusedLabel", 50, "Remove unused label"),
    ("dart.fix.remove.unusedLocalVariable", 50, "Remove unused local variable"),
    ("dart.fix.remove.unusedParameter", 50, "Remove the unused parameter"),
    ("dart.fix.remove.unusedParameter.multi", 40, "Remove unused parameters everywhere in file"),
    ("dart.fix.remove.var", 50, "Remove 'var'"),
    ("dart.fix.remove.var.keyword", 50, "Remove 'var'"),
    ("dart.fix.rename.methodParameter", 50, "Rename '{0}' to '{1}'"),
    ("dart.fix.rename.toCamelCase", 50, "Rename to '{0}'"),
    ("dart.fix.rename.toCamelCase.multi", 40, "Rename to camel case everywhere in file"),
    ("dart.fix.replace.booleanWithBool", 50, "Replace 'boolean' with 'bool'"),
    ("dart.fix.replace.booleanWithBool.multi", 40, "Replace all 'boolean's with 'bool' in file"),
    ("dart.fix.replace.cascadeWithDot", 50, "Replace '..' with '.'"),
    ("dart.fix.replace.cascadeWithDot.multi", 40, "Replace unnecessary '..'s with '.'s everywhere in file"),
    ("dart.fix.replace.colonWithEquals", 50, "Replace ':' with '='"),
    ("dart.fix.replace.colonWithEquals.multi", 40, "Replace ':'s with '='s everywhere in file"),
    ("dart.fix.replace.colonWithIn", 50, "Replace ':' with 'in'"),
    ("dart.fix.replace.colonWithIn.multi", 40, "Replace ':'s with 'in's everywhere in file"),
    ("dart.fix.replace.containerWithColoredBox", 50, "Replace with 'ColoredBox'"),
    ("dart.fix.replace.containerWithColoredBox.multi", 40, "Replace with 'ColoredBox' everywhere in file"),
    ("dart.fix.replace.containerWithSizedBox", 50, "Replace with 'SizedBox'"),
    ("dart.fix.replace.containerWithSizedBox.multi", 40, "Replace with 'SizedBox' everywhere in file"),
    ("dart.fix.replace.finalWithConst", 50, "Replace 'final' with 'const'"),
    ("dart.fix.replace.finalWithConst.multi", 40, "Replace 'final' with 'const' where possible in file"),
    ("dart.fix.replace.finalWithVar", 50, "Replace 'final' with 'var'"),
    ("dart.fix.replace.finalWithVar.multi", 40, "Replace 'final' with 'var' where possible in file"),
    ("dart.fix.replace.newWithConst", 50, "Replace 'new' with 'const'"),
    ("dart.fix.replace.newWithConst.multi", 40, "Replace 'new' with 'const' where possible in file"),
    ("dart.fix.replace.nullCheckWithCast", 50, "Replace null check with a cast"),
    ("dart.fix.replace.nullCheckWithCast.multi", 40, "Replace null checks with casts in file"),
    ("dart.fix.replace.nullWithClosure", 50, "Replace 'null' with a closure"),
    ("dart.fix.replace.nullWithClosure.multi", 40, "Replace 'null's with closures where possible in file"),
    ("dart.fix.replace.nullWithVoid", 50, "Replace 'Null' with 'void'"),
    ("dart.fix.replace.nullWithVoid.multi", 40, "Replace 'Null' with 'void' everywhere in file"),
    ("dart.fix.replace.returnType", 50, "Replace the return type with '{0}'"),
    ("dart.fix.replace.returnTypeFuture", 50, "Return 'Future<{0}>'"),
    ("dart.fix.replace.returnTypeFuture.multi", 40, "Return a 'Future' where required in file"),
    ("dart.fix.replace.returnTypeIterable", 50, "Return 'Iterable<{0}>'"),
    ("dart.fix.replace.returnTypeStream", 50, "Return 'Stream<{0}>'"),
    ("dart.fix.replace.varWithDynamic", 50, "Replace 'var' with 'dynamic'"),
    ("dart.fix.replace.withArrow", 50, "Replace with '=>'"),
    ("dart.fix.replace.withArrow.multi", 50, "Replace with '=>' everywhere in file"),
    ("dart.fix.replace.withBrackets", 50, "Replace with { }"),
    ("dart.fix.replace.withBrackets.multi", 40, "Replace with { } everywhere in file"),
    ("dart.fix.replace.withConditionalAssignment", 50, "Replace with ??="),
    ("dart.fix.replace.withConditionalAssignment.multi", 40, "Replace with ??= everywhere in file"),
    ("dart.fix.replace.withDecoratedBox", 50, "Replace with 'DecoratedBox'"),
    ("dart.fix.replace.withDecoratedBox.multi", 40, "Replace with 'DecoratedBox' everywhere in file"),
    ("dart.fix.replace.withEightDigitHex", 50, "Replace with '{0}'"),
    ("dart.fix.replace.withEightDigitHex.multi", 40, "Replace with hex digits everywhere in file"),
    ("dart.fix.replace.withExtensionName", 50, "Replace with '{0}'"),
    ("dart.fix.replace.withIdentifier", 50, "Replace with identifier"),
    ("dart.fix.replace.withIdentifier.multi", 40, "Replace with identifier everywhere in file"),
    ("dart.fix.replace.withInterpolation", 50, "Replace with interpolation"),
    ("dart.fix.replace.withInterpolation.multi", 40, "Replace with interpolations everywhere in file"),
    ("dart.fix.replace.withIsEmpty", 50, "Replace with 'isEmpty'"),
    ("dart.fix.replace.withIsEmpty.multi", 40, "Replace with 'isEmpty' everywhere in file"),
    ("dart.fix.replace.withIsNaN", 50, "Replace the condition with '.isNaN'"),
    ("dart.fix.replace.withIsNotEmpty", 50, "Replace with 'isNotEmpty'"),
    ("dart.fix.replace.withIsNotEmpty.multi", 40, "Replace with 'isNotEmpty' everywhere in file"),
    ("dart.fix.replace.withNotNullAware", 50, "Replace with '{0}'"),
    ("dart.fix.replace.withNotNullAware.multi", 40, "Replace with non-null-aware operator everywhere in file"),
    ("dart.fix.replace.withNullAware", 50, "Replace the '{0}' with a '{1}' in the invocation"),
    ("dart.fix.replace.withPartOfUri", 50, "Replace with 'part of {0}'"),
    ("dart.fix.replace.withTearOff", 50, "Replace function literal with tear-off"),
    ("dart.fix.replace.withTearOff.multi", 40, "Replace function literals with tear-offs everywhere in file"),
    ("dart.fix.replace.withUnicodeEscape", 50, "Replace with Unicode escape"),
    ("dart.fix.replace.withVar", 50, "Replace type annotation with 'var'"),
    ("dart.fix.replace.withVar.multi", 40, "Replace type annotations with 'var' everywhere in file"),
    ("dart.fix.replace.withWildcard", 50, "Replace with '_'"),
    ("dart.fix.replace.withWildcard.multi", 50, "Replace with '_' everywhere in file"),
    ("dart.fix.sort.childPropertyLast", 50, "Move child property to end of arguments"),
    ("dart.fix.sort.childPropertyLast.multi", 40, "Move child properties to ends of arguments everywhere in file"),
    ("dart.fix.sort.combinators", 50, "Sort combinators"),
    ("dart.fix.sort.combinators.multi", 40, "Sort combinators everywhere in file"),
    ("dart.fix.sort.sortConstructorFirst", 50, "Move before other members"),
    ("dart.fix.sort.sortConstructorFirst.multi", 50, "Move all constructors before other members"),
    ("dart.fix.sort.sortUnnamedConstructorFirst", 50, "Move before named constructors"),
    ("dart.fix.sort.sortUnnamedConstructorFirst.multi", 50, "Move all unnamed constructors before named constructors"),
    ("dart.fix.split.multipleDeclarations", 50, "Split multiple declarations into multiple lines"),
    ("dart.fix.split.multipleDeclarations.multi", 50, "Split all multiple declarations into multiple lines"),
    ("dart.fix.surround.parentheses", 50, "Surround with parentheses"),
    ("dart.fix.updateSdkConstraints", 50, "Update the SDK constraints"),
    ("dart.fix.use.effectiveIntegerDivision", 50, "Use effective integer division ~/"),
    ("dart.fix.use.effectiveIntegerDivision.multi", 40, "Use effective integer division ~/ everywhere in file"),
    ("dart.fix.use.eqEqNull", 50, "Use == null instead of 'is Null'"),
    ("dart.fix.use.eqEqNull.multi", 40, "Use == null instead of 'is Null' everywhere in file"),
    ("dart.fix.use.isNotEmpty", 50, "Use x.isNotEmpty instead of '!x.isEmpty'"),
    ("dart.fix.use.isNotEmpty.multi", 40, "Use x.isNotEmpty instead of '!x.isEmpty' everywhere in file"),
    ("dart.fix.use.namedConstants", 50, "Replace with a predefined named constant"),
    ("dart.fix.use.notEqNull", 50, "Use != null instead of 'is! Null'"),
    ("dart.fix.use.notEqNull.multi", 40, "Use != null instead of 'is! Null' everywhere in file"),
    ("dart.fix.use.rethrow", 50, "Replace throw with rethrow"),
    ("dart.fix.use.rethrow.multi", 40, "Replace throw with rethrow where possible in file"),
    ("dart.fix.wrap.unawaited", 50, "Wrap in 'unawaited'"),
];
