[package]
name = "dartforge-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[lints]
workspace = true
[dependencies]
dartforge-hir = { path = "../hir" }
serde_json = "1"
dartforge-syntax = { path = "../syntax" }
dartforge-diagnostics = { path = "../diagnostics" }

[[bench]]
name = "classes"
harness = false
