// GERADO por `scripts/gerar-tabelas-analise.py` (frente INFRA-FASES). NÃO EDITE.
// Fonte: `linter/lib/src/rules.dart` (ordem do registro) e `linter/lib/src/rules/**.dart`
// (nome, `state:`, `incompatibleRules`) do SDK 3.6.2; conjuntos de `package:lints` 5.1.1.

use super::{Conjunto, EstadoDaRegra, InfoRegra};

/// As 240 regras registradas por `registerLintRules()`, na ordem do registro.
pub static REGRAS: [InfoRegra; 240] = [
    InfoRegra { nome: "always_declare_return_types", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/always_declare_return_types.dart" },
    InfoRegra { nome: "always_put_control_body_on_new_line", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/always_put_control_body_on_new_line.dart" },
    InfoRegra { nome: "always_put_required_named_parameters_first", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/always_put_required_named_parameters_first.dart" },
    InfoRegra { nome: "always_require_non_null_named_parameters", estado: EstadoDaRegra::Removida, desde: Some((3, 3, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/always_require_non_null_named_parameters.dart" },
    InfoRegra { nome: "always_specify_types", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["avoid_types_on_closure_parameters", "omit_local_variable_types", "omit_obvious_local_variable_types"], conjunto: Conjunto::Nenhum, arquivo: "rules/always_specify_types.dart" },
    InfoRegra { nome: "always_use_package_imports", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["prefer_relative_imports"], conjunto: Conjunto::Nenhum, arquivo: "rules/always_use_package_imports.dart" },
    InfoRegra { nome: "analyzer_use_new_elements", estado: EstadoDaRegra::Interna, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/analyzer_use_new_elements.dart" },
    InfoRegra { nome: "annotate_overrides", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/annotate_overrides.dart" },
    InfoRegra { nome: "annotate_redeclares", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/annotate_redeclares.dart" },
    InfoRegra { nome: "avoid_annotating_with_dynamic", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_annotating_with_dynamic.dart" },
    InfoRegra { nome: "avoid_as", estado: EstadoDaRegra::Removida, desde: Some((2, 12, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_as.dart" },
    InfoRegra { nome: "avoid_bool_literals_in_conditional_expressions", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_bool_literals_in_conditional_expressions.dart" },
    InfoRegra { nome: "avoid_catches_without_on_clauses", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_catches_without_on_clauses.dart" },
    InfoRegra { nome: "avoid_catching_errors", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_catching_errors.dart" },
    InfoRegra { nome: "avoid_classes_with_only_static_members", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_classes_with_only_static_members.dart" },
    InfoRegra { nome: "avoid_double_and_int_checks", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_double_and_int_checks.dart" },
    InfoRegra { nome: "avoid_dynamic_calls", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_dynamic_calls.dart" },
    InfoRegra { nome: "avoid_empty_else", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/avoid_empty_else.dart" },
    InfoRegra { nome: "avoid_equals_and_hash_code_on_mutable_classes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_equals_and_hash_code_on_mutable_classes.dart" },
    InfoRegra { nome: "avoid_escaping_inner_quotes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_escaping_inner_quotes.dart" },
    InfoRegra { nome: "avoid_field_initializers_in_const_classes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_field_initializers_in_const_classes.dart" },
    InfoRegra { nome: "avoid_final_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["prefer_final_parameters"], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_final_parameters.dart" },
    InfoRegra { nome: "avoid_function_literals_in_foreach_calls", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/avoid_function_literals_in_foreach_calls.dart" },
    InfoRegra { nome: "avoid_futureor_void", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_futureor_void.dart" },
    InfoRegra { nome: "avoid_implementing_value_types", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_implementing_value_types.dart" },
    InfoRegra { nome: "avoid_init_to_null", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/avoid_init_to_null.dart" },
    InfoRegra { nome: "avoid_js_rounded_ints", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_js_rounded_ints.dart" },
    InfoRegra { nome: "avoid_multiple_declarations_per_line", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_multiple_declarations_per_line.dart" },
    InfoRegra { nome: "avoid_null_checks_in_equality_operators", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_null_checks_in_equality_operators.dart" },
    InfoRegra { nome: "avoid_positional_boolean_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_positional_boolean_parameters.dart" },
    InfoRegra { nome: "avoid_print", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_print.dart" },
    InfoRegra { nome: "avoid_private_typedef_functions", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_private_typedef_functions.dart" },
    InfoRegra { nome: "avoid_redundant_argument_values", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_redundant_argument_values.dart" },
    InfoRegra { nome: "avoid_relative_lib_imports", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/avoid_relative_lib_imports.dart" },
    InfoRegra { nome: "avoid_renaming_method_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/avoid_renaming_method_parameters.dart" },
    InfoRegra { nome: "avoid_return_types_on_setters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/avoid_return_types_on_setters.dart" },
    InfoRegra { nome: "avoid_returning_null", estado: EstadoDaRegra::Removida, desde: Some((3, 3, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_returning_null.dart" },
    InfoRegra { nome: "avoid_returning_null_for_future", estado: EstadoDaRegra::Removida, desde: Some((3, 3, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_returning_null_for_future.dart" },
    InfoRegra { nome: "avoid_returning_null_for_void", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/avoid_returning_null_for_void.dart" },
    InfoRegra { nome: "avoid_returning_this", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_returning_this.dart" },
    InfoRegra { nome: "avoid_setters_without_getters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_setters_without_getters.dart" },
    InfoRegra { nome: "avoid_shadowing_type_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/avoid_shadowing_type_parameters.dart" },
    InfoRegra { nome: "avoid_single_cascade_in_expression_statements", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/avoid_single_cascade_in_expression_statements.dart" },
    InfoRegra { nome: "avoid_slow_async_io", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_slow_async_io.dart" },
    InfoRegra { nome: "avoid_type_to_string", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_type_to_string.dart" },
    InfoRegra { nome: "avoid_types_as_parameter_names", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/avoid_types_as_parameter_names.dart" },
    InfoRegra { nome: "avoid_types_on_closure_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["always_specify_types"], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_types_on_closure_parameters.dart" },
    InfoRegra { nome: "avoid_unnecessary_containers", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_unnecessary_containers.dart" },
    InfoRegra { nome: "avoid_unstable_final_fields", estado: EstadoDaRegra::Removida, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_unstable_final_fields.dart" },
    InfoRegra { nome: "avoid_unused_constructor_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_unused_constructor_parameters.dart" },
    InfoRegra { nome: "avoid_void_async", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_void_async.dart" },
    InfoRegra { nome: "avoid_web_libraries_in_flutter", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/avoid_web_libraries_in_flutter.dart" },
    InfoRegra { nome: "await_only_futures", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/await_only_futures.dart" },
    InfoRegra { nome: "camel_case_extensions", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/camel_case_extensions.dart" },
    InfoRegra { nome: "camel_case_types", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/camel_case_types.dart" },
    InfoRegra { nome: "cancel_subscriptions", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/cancel_subscriptions.dart" },
    InfoRegra { nome: "cascade_invocations", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/cascade_invocations.dart" },
    InfoRegra { nome: "cast_nullable_to_non_nullable", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/cast_nullable_to_non_nullable.dart" },
    InfoRegra { nome: "close_sinks", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/close_sinks.dart" },
    InfoRegra { nome: "collection_methods_unrelated_type", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/collection_methods_unrelated_type.dart" },
    InfoRegra { nome: "combinators_ordering", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/combinators_ordering.dart" },
    InfoRegra { nome: "comment_references", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/comment_references.dart" },
    InfoRegra { nome: "conditional_uri_does_not_exist", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/conditional_uri_does_not_exist.dart" },
    InfoRegra { nome: "constant_identifier_names", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/constant_identifier_names.dart" },
    InfoRegra { nome: "control_flow_in_finally", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/control_flow_in_finally.dart" },
    InfoRegra { nome: "curly_braces_in_flow_control_structures", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/curly_braces_in_flow_control_structures.dart" },
    InfoRegra { nome: "dangling_library_doc_comments", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/dangling_library_doc_comments.dart" },
    InfoRegra { nome: "depend_on_referenced_packages", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/pub/depend_on_referenced_packages.dart" },
    InfoRegra { nome: "deprecated_consistency", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/deprecated_consistency.dart" },
    InfoRegra { nome: "deprecated_member_use_from_same_package", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/deprecated_member_use_from_same_package.dart" },
    InfoRegra { nome: "diagnostic_describe_all_properties", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/diagnostic_describe_all_properties.dart" },
    InfoRegra { nome: "directives_ordering", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/directives_ordering.dart" },
    InfoRegra { nome: "discarded_futures", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/discarded_futures.dart" },
    InfoRegra { nome: "document_ignores", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/document_ignores.dart" },
    InfoRegra { nome: "do_not_use_environment", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/do_not_use_environment.dart" },
    InfoRegra { nome: "empty_catches", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/empty_catches.dart" },
    InfoRegra { nome: "empty_constructor_bodies", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/empty_constructor_bodies.dart" },
    InfoRegra { nome: "empty_statements", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/empty_statements.dart" },
    InfoRegra { nome: "enable_null_safety", estado: EstadoDaRegra::Removida, desde: Some((3, 0, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/enable_null_safety.dart" },
    InfoRegra { nome: "eol_at_end_of_file", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/eol_at_end_of_file.dart" },
    InfoRegra { nome: "erase_dart_type_extension_types", estado: EstadoDaRegra::Interna, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/erase_dart_type_extension_types.dart" },
    InfoRegra { nome: "exhaustive_cases", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/exhaustive_cases.dart" },
    InfoRegra { nome: "file_names", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/file_names.dart" },
    InfoRegra { nome: "flutter_style_todos", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/flutter_style_todos.dart" },
    InfoRegra { nome: "hash_and_equals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/hash_and_equals.dart" },
    InfoRegra { nome: "implementation_imports", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/implementation_imports.dart" },
    InfoRegra { nome: "implicit_call_tearoffs", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/implicit_call_tearoffs.dart" },
    InfoRegra { nome: "implicit_reopen", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/implicit_reopen.dart" },
    InfoRegra { nome: "invalid_case_patterns", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/invalid_case_patterns.dart" },
    InfoRegra { nome: "invariant_booleans", estado: EstadoDaRegra::Removida, desde: Some((3, 0, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/invariant_booleans.dart" },
    InfoRegra { nome: "iterable_contains_unrelated_type", estado: EstadoDaRegra::Removida, desde: Some((3, 3, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/iterable_contains_unrelated_type.dart" },
    InfoRegra { nome: "invalid_runtime_check_with_js_interop_types", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/invalid_runtime_check_with_js_interop_types.dart" },
    InfoRegra { nome: "join_return_with_assignment", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/join_return_with_assignment.dart" },
    InfoRegra { nome: "leading_newlines_in_multiline_strings", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/leading_newlines_in_multiline_strings.dart" },
    InfoRegra { nome: "library_annotations", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/library_annotations.dart" },
    InfoRegra { nome: "library_names", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/library_names.dart" },
    InfoRegra { nome: "library_prefixes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/library_prefixes.dart" },
    InfoRegra { nome: "library_private_types_in_public_api", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/library_private_types_in_public_api.dart" },
    InfoRegra { nome: "lines_longer_than_80_chars", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/lines_longer_than_80_chars.dart" },
    InfoRegra { nome: "list_remove_unrelated_type", estado: EstadoDaRegra::Removida, desde: Some((3, 3, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/list_remove_unrelated_type.dart" },
    InfoRegra { nome: "literal_only_boolean_expressions", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/literal_only_boolean_expressions.dart" },
    InfoRegra { nome: "matching_super_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/matching_super_parameters.dart" },
    InfoRegra { nome: "missing_code_block_language_in_doc_comment", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/missing_code_block_language_in_doc_comment.dart" },
    InfoRegra { nome: "missing_whitespace_between_adjacent_strings", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/missing_whitespace_between_adjacent_strings.dart" },
    InfoRegra { nome: "no_adjacent_strings_in_list", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/no_adjacent_strings_in_list.dart" },
    InfoRegra { nome: "no_default_cases", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/no_default_cases.dart" },
    InfoRegra { nome: "no_duplicate_case_values", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/no_duplicate_case_values.dart" },
    InfoRegra { nome: "no_leading_underscores_for_library_prefixes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/no_leading_underscores_for_library_prefixes.dart" },
    InfoRegra { nome: "no_leading_underscores_for_local_identifiers", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/no_leading_underscores_for_local_identifiers.dart" },
    InfoRegra { nome: "no_literal_bool_comparisons", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/no_literal_bool_comparisons.dart" },
    InfoRegra { nome: "no_logic_in_create_state", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/no_logic_in_create_state.dart" },
    InfoRegra { nome: "no_runtimeType_toString", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/no_runtimeType_toString.dart" },
    InfoRegra { nome: "no_self_assignments", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/no_self_assignments.dart" },
    InfoRegra { nome: "no_wildcard_variable_uses", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/no_wildcard_variable_uses.dart" },
    InfoRegra { nome: "non_constant_identifier_names", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/non_constant_identifier_names.dart" },
    InfoRegra { nome: "noop_primitive_operations", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/noop_primitive_operations.dart" },
    InfoRegra { nome: "null_check_on_nullable_type_parameter", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/null_check_on_nullable_type_parameter.dart" },
    InfoRegra { nome: "null_closures", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/null_closures.dart" },
    InfoRegra { nome: "omit_local_variable_types", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["always_specify_types", "specify_nonobvious_local_variable_types"], conjunto: Conjunto::Nenhum, arquivo: "rules/omit_local_variable_types.dart" },
    InfoRegra { nome: "omit_obvious_local_variable_types", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &["always_specify_types"], conjunto: Conjunto::Nenhum, arquivo: "rules/omit_obvious_local_variable_types.dart" },
    InfoRegra { nome: "one_member_abstracts", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/one_member_abstracts.dart" },
    InfoRegra { nome: "only_throw_errors", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/only_throw_errors.dart" },
    InfoRegra { nome: "overridden_fields", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/overridden_fields.dart" },
    InfoRegra { nome: "package_api_docs", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/package_api_docs.dart" },
    InfoRegra { nome: "package_names", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/pub/package_names.dart" },
    InfoRegra { nome: "package_prefixed_library_names", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/package_prefixed_library_names.dart" },
    InfoRegra { nome: "parameter_assignments", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/parameter_assignments.dart" },
    InfoRegra { nome: "prefer_adjacent_string_concatenation", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_adjacent_string_concatenation.dart" },
    InfoRegra { nome: "prefer_asserts_in_initializer_lists", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_asserts_in_initializer_lists.dart" },
    InfoRegra { nome: "prefer_asserts_with_message", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_asserts_with_message.dart" },
    InfoRegra { nome: "prefer_bool_in_asserts", estado: EstadoDaRegra::Removida, desde: Some((3, 0, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_bool_in_asserts.dart" },
    InfoRegra { nome: "prefer_collection_literals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_collection_literals.dart" },
    InfoRegra { nome: "prefer_conditional_assignment", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_conditional_assignment.dart" },
    InfoRegra { nome: "prefer_const_constructors", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_const_constructors.dart" },
    InfoRegra { nome: "prefer_const_constructors_in_immutables", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_const_constructors_in_immutables.dart" },
    InfoRegra { nome: "prefer_const_declarations", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_const_declarations.dart" },
    InfoRegra { nome: "prefer_const_literals_to_create_immutables", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_const_literals_to_create_immutables.dart" },
    InfoRegra { nome: "prefer_constructors_over_static_methods", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_constructors_over_static_methods.dart" },
    InfoRegra { nome: "prefer_contains", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_contains.dart" },
    InfoRegra { nome: "prefer_double_quotes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["prefer_single_quotes"], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_double_quotes.dart" },
    InfoRegra { nome: "prefer_equal_for_default_values", estado: EstadoDaRegra::Removida, desde: Some((3, 0, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_equal_for_default_values.dart" },
    InfoRegra { nome: "prefer_expression_function_bodies", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_expression_function_bodies.dart" },
    InfoRegra { nome: "prefer_final_fields", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_final_fields.dart" },
    InfoRegra { nome: "prefer_final_in_for_each", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_final_in_for_each.dart" },
    InfoRegra { nome: "prefer_final_locals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["unnecessary_final"], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_final_locals.dart" },
    InfoRegra { nome: "prefer_final_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["unnecessary_final", "avoid_final_parameters"], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_final_parameters.dart" },
    InfoRegra { nome: "prefer_for_elements_to_map_fromIterable", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_for_elements_to_map_fromIterable.dart" },
    InfoRegra { nome: "prefer_foreach", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_foreach.dart" },
    InfoRegra { nome: "prefer_function_declarations_over_variables", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_function_declarations_over_variables.dart" },
    InfoRegra { nome: "prefer_generic_function_type_aliases", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/prefer_generic_function_type_aliases.dart" },
    InfoRegra { nome: "prefer_if_elements_to_conditional_expressions", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_if_elements_to_conditional_expressions.dart" },
    InfoRegra { nome: "prefer_if_null_operators", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_if_null_operators.dart" },
    InfoRegra { nome: "prefer_initializing_formals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_initializing_formals.dart" },
    InfoRegra { nome: "prefer_inlined_adds", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_inlined_adds.dart" },
    InfoRegra { nome: "prefer_int_literals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_int_literals.dart" },
    InfoRegra { nome: "prefer_interpolation_to_compose_strings", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_interpolation_to_compose_strings.dart" },
    InfoRegra { nome: "prefer_is_empty", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/prefer_is_empty.dart" },
    InfoRegra { nome: "prefer_is_not_empty", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/prefer_is_not_empty.dart" },
    InfoRegra { nome: "prefer_is_not_operator", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_is_not_operator.dart" },
    InfoRegra { nome: "prefer_iterable_whereType", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/prefer_iterable_whereType.dart" },
    InfoRegra { nome: "prefer_mixin", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_mixin.dart" },
    InfoRegra { nome: "prefer_null_aware_method_calls", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_null_aware_method_calls.dart" },
    InfoRegra { nome: "prefer_null_aware_operators", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_null_aware_operators.dart" },
    InfoRegra { nome: "prefer_relative_imports", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["always_use_package_imports"], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_relative_imports.dart" },
    InfoRegra { nome: "prefer_single_quotes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["prefer_double_quotes"], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_single_quotes.dart" },
    InfoRegra { nome: "prefer_spread_collections", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/prefer_spread_collections.dart" },
    InfoRegra { nome: "prefer_typing_uninitialized_variables", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/prefer_typing_uninitialized_variables.dart" },
    InfoRegra { nome: "prefer_void_to_null", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/prefer_void_to_null.dart" },
    InfoRegra { nome: "provide_deprecation_message", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/provide_deprecation_message.dart" },
    InfoRegra { nome: "public_member_api_docs", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/public_member_api_docs.dart" },
    InfoRegra { nome: "recursive_getters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/recursive_getters.dart" },
    InfoRegra { nome: "require_trailing_commas", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/require_trailing_commas.dart" },
    InfoRegra { nome: "secure_pubspec_urls", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/pub/secure_pubspec_urls.dart" },
    InfoRegra { nome: "sized_box_for_whitespace", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/sized_box_for_whitespace.dart" },
    InfoRegra { nome: "sized_box_shrink_expand", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/sized_box_shrink_expand.dart" },
    InfoRegra { nome: "slash_for_doc_comments", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/slash_for_doc_comments.dart" },
    InfoRegra { nome: "sort_child_properties_last", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/sort_child_properties_last.dart" },
    InfoRegra { nome: "sort_constructors_first", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/sort_constructors_first.dart" },
    InfoRegra { nome: "sort_pub_dependencies", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/pub/sort_pub_dependencies.dart" },
    InfoRegra { nome: "sort_unnamed_constructors_first", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/sort_unnamed_constructors_first.dart" },
    InfoRegra { nome: "super_goes_last", estado: EstadoDaRegra::Removida, desde: Some((3, 0, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/super_goes_last.dart" },
    InfoRegra { nome: "specify_nonobvious_local_variable_types", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &["omit_local_variable_types"], conjunto: Conjunto::Nenhum, arquivo: "rules/specify_nonobvious_local_variable_types.dart" },
    InfoRegra { nome: "test_types_in_equals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/test_types_in_equals.dart" },
    InfoRegra { nome: "throw_in_finally", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/throw_in_finally.dart" },
    InfoRegra { nome: "tighten_type_of_initializing_formals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/tighten_type_of_initializing_formals.dart" },
    InfoRegra { nome: "type_annotate_public_apis", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/type_annotate_public_apis.dart" },
    InfoRegra { nome: "type_init_formals", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/type_init_formals.dart" },
    InfoRegra { nome: "type_literal_in_constant_pattern", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/type_literal_in_constant_pattern.dart" },
    InfoRegra { nome: "unawaited_futures", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unawaited_futures.dart" },
    InfoRegra { nome: "unintended_html_in_doc_comment", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/unintended_html_in_doc_comment.dart" },
    InfoRegra { nome: "unnecessary_await_in_return", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_await_in_return.dart" },
    InfoRegra { nome: "unnecessary_brace_in_string_interps", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_brace_in_string_interps.dart" },
    InfoRegra { nome: "unnecessary_breaks", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_breaks.dart" },
    InfoRegra { nome: "unnecessary_const", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_const.dart" },
    InfoRegra { nome: "unnecessary_constructor_name", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_constructor_name.dart" },
    InfoRegra { nome: "unnecessary_final", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &["prefer_final_locals", "prefer_final_parameters"], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_final.dart" },
    InfoRegra { nome: "unnecessary_getters_setters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_getters_setters.dart" },
    InfoRegra { nome: "unnecessary_lambdas", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_lambdas.dart" },
    InfoRegra { nome: "unnecessary_late", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_late.dart" },
    InfoRegra { nome: "unnecessary_library_directive", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_library_directive.dart" },
    InfoRegra { nome: "unnecessary_library_name", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_library_name.dart" },
    InfoRegra { nome: "unnecessary_new", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_new.dart" },
    InfoRegra { nome: "unnecessary_null_aware_assignments", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_null_aware_assignments.dart" },
    InfoRegra { nome: "unnecessary_null_aware_operator_on_extension_on_nullable", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_null_aware_operator_on_extension_on_nullable.dart" },
    InfoRegra { nome: "unnecessary_null_checks", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_null_checks.dart" },
    InfoRegra { nome: "unnecessary_null_in_if_null_operators", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_null_in_if_null_operators.dart" },
    InfoRegra { nome: "unnecessary_nullable_for_final_variable_declarations", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_nullable_for_final_variable_declarations.dart" },
    InfoRegra { nome: "unnecessary_overrides", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/unnecessary_overrides.dart" },
    InfoRegra { nome: "unnecessary_parenthesis", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_parenthesis.dart" },
    InfoRegra { nome: "unnecessary_raw_strings", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_raw_strings.dart" },
    InfoRegra { nome: "unnecessary_statements", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unnecessary_statements.dart" },
    InfoRegra { nome: "unnecessary_string_escapes", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_string_escapes.dart" },
    InfoRegra { nome: "unnecessary_string_interpolations", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_string_interpolations.dart" },
    InfoRegra { nome: "unnecessary_this", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_this.dart" },
    InfoRegra { nome: "unnecessary_to_list_in_spreads", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/unnecessary_to_list_in_spreads.dart" },
    InfoRegra { nome: "unreachable_from_main", estado: EstadoDaRegra::Estavel, desde: Some((3, 1, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unreachable_from_main.dart" },
    InfoRegra { nome: "unrelated_type_equality_checks", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/unrelated_type_equality_checks.dart" },
    InfoRegra { nome: "unsafe_html", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/unsafe_html.dart" },
    InfoRegra { nome: "use_build_context_synchronously", estado: EstadoDaRegra::Estavel, desde: Some((3, 2, 0)), incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_build_context_synchronously.dart" },
    InfoRegra { nome: "use_colored_box", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_colored_box.dart" },
    InfoRegra { nome: "use_decorated_box", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_decorated_box.dart" },
    InfoRegra { nome: "use_enums", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_enums.dart" },
    InfoRegra { nome: "use_full_hex_values_for_flutter_colors", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_full_hex_values_for_flutter_colors.dart" },
    InfoRegra { nome: "use_function_type_syntax_for_parameters", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/use_function_type_syntax_for_parameters.dart" },
    InfoRegra { nome: "use_if_null_to_convert_nulls_to_bools", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_if_null_to_convert_nulls_to_bools.dart" },
    InfoRegra { nome: "use_is_even_rather_than_modulo", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_is_even_rather_than_modulo.dart" },
    InfoRegra { nome: "use_key_in_widget_constructors", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_key_in_widget_constructors.dart" },
    InfoRegra { nome: "use_late_for_private_fields_and_variables", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_late_for_private_fields_and_variables.dart" },
    InfoRegra { nome: "use_named_constants", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_named_constants.dart" },
    InfoRegra { nome: "use_raw_strings", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_raw_strings.dart" },
    InfoRegra { nome: "use_rethrow_when_possible", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/use_rethrow_when_possible.dart" },
    InfoRegra { nome: "use_setters_to_change_properties", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_setters_to_change_properties.dart" },
    InfoRegra { nome: "use_string_buffers", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_string_buffers.dart" },
    InfoRegra { nome: "use_string_in_part_of_directives", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/use_string_in_part_of_directives.dart" },
    InfoRegra { nome: "use_super_parameters", estado: EstadoDaRegra::Experimental, desde: None, incompativeis: &[], conjunto: Conjunto::Recommended, arquivo: "rules/use_super_parameters.dart" },
    InfoRegra { nome: "use_test_throws_matchers", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_test_throws_matchers.dart" },
    InfoRegra { nome: "use_to_and_as_if_applicable", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_to_and_as_if_applicable.dart" },
    InfoRegra { nome: "use_truncating_division", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Nenhum, arquivo: "rules/use_truncating_division.dart" },
    InfoRegra { nome: "valid_regexps", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/valid_regexps.dart" },
    InfoRegra { nome: "void_checks", estado: EstadoDaRegra::Estavel, desde: None, incompativeis: &[], conjunto: Conjunto::Core, arquivo: "rules/void_checks.dart" },
];
