[package]
name = "dartforge-llvm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[lints]
workspace = true
[dependencies]
dartforge-hir = { path = "../hir" }
dartforge-syntax = { path = "../syntax" }
dartforge-diagnostics = { path = "../diagnostics" }
[dev-dependencies]
dartforge-lexer = { path = "../lexer" }
dartforge-parser = { path = "../parser" }
dartforge-semantic = { path = "../semantic" }
dartforge-native = { path = "../native" }
